"""Add ngo models

Revision ID: 3c9ddb84dde6
Revises: 791414c06c1d
Create Date: 2026-05-08 14:02:01.662889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9ddb84dde6'
down_revision: Union[str, Sequence[str], None] = '791414c06c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngo_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngo_roles_id'), 'ngo_roles', ['id'], unique=False)
    op.create_index(op.f('ix_ngo_roles_name'), 'ngo_roles', ['name'], unique=True)
    op.create_table('ngos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'private', name='ngovisibility'), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='ngoverificationstatus'), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngos_id'), 'ngos', ['id'], unique=False)
    op.create_index(op.f('ix_ngos_invite_code'), 'ngos', ['invite_code'], unique=True)
    op.create_index(op.f('ix_ngos_slug'), 'ngos', ['slug'], unique=True)
    op.create_table('ngo_members',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ngo_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ngo_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'ngo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ngo_members')
    op.drop_index(op.f('ix_ngos_slug'), table_name='ngos')
    op.drop_index(op.f('ix_ngos_invite_code'), table_name='ngos')
    op.drop_index(op.f('ix_ngos_id'), table_name='ngos')
    op.drop_table('ngos')
    op.drop_index(op.f('ix_ngo_roles_name'), table_name='ngo_roles')
    op.drop_index(op.f('ix_ngo_roles_id'), table_name='ngo_roles')
    op.drop_table('ngo_roles')
    # ### end Alembic commands ###
