"""Add device registrations

Revision ID: a6f38cae90a3
Revises: 192965d3bbdf
Create Date: 2026-05-13 06:17:00.898410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a6f38cae90a3'
down_revision: Union[str, Sequence[str], None] = '192965d3bbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_registrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_registrations_device_token'), 'device_registrations', ['device_token'], unique=True)
    op.create_index(op.f('ix_device_registrations_id'), 'device_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_device_registrations_user_id'), 'device_registrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_registrations_user_id'), table_name='device_registrations')
    op.drop_index(op.f('ix_device_registrations_id'), table_name='device_registrations')
    op.drop_index(op.f('ix_device_registrations_device_token'), table_name='device_registrations')
    op.drop_table('device_registrations')
    # ### end Alembic commands ###
